apiVersion: v1
kind: Service
metadata:
    name: nginix
spec:
    type: {{ .Values.service.type }}
    selector: 
        tier: frontend
        app: nginx
    ports:
    - name: nginx-svc-port
      protocol: TCP
      port: {{ Values.service.port }}
      targetPort: 80